version: 2
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=auto
    goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
signs:
  - artifacts: checksum
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
