builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=auto
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
signs:
  - artifacts: checksum
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
