name: 'publish docker image'

on:
  repository_dispatch:
    types: [publish]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: download ama.ne.jp archive
      run: |
        curl -so ./amanejp.zip https://amanejp.netlify.app/appendices/archive/amanejp.zip || while ! curl --continue-at - -so ./amanejp.zip https://amanejp.netlify.app/appendices/archive/amanejp.zip; do :; done
        unzip -q ./amanejp.zip
    - name: build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: amane/amanejp:latest
